# Generated by Django 3.1.7 on 2021-03-27 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, verbose_name='Location Name')),
                ('current_estimated_population', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Current Estimated Population')),
                ('api_endpoint', models.URLField(verbose_name='API Endpoint')),
                ('resource_url', models.URLField(verbose_name='URL of Resource')),
            ],
        ),
    ]
