# Generated by Django 3.1.7 on 2021-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('current_estimated_population', models.PositiveIntegerField()),
                ('api_endpoint', models.CharField(max_length=200)),
                ('resource_url', models.CharField(max_length=200, verbose_name='URL of Resource')),
            ],
        ),
    ]
