# Generated by Django 3.1.7 on 2021-03-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='api_endpoint',
            field=models.CharField(max_length=200, verbose_name='API Endpoint'),
        ),
        migrations.AlterField(
            model_name='location',
            name='current_estimated_population',
            field=models.PositiveIntegerField(verbose_name='Current Estimated Population'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=200, verbose_name='Location Name'),
        ),
    ]
