# Generated by Django 3.1.7 on 2021-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_viewer', '0002_auto_20210325_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='api_endpoint',
            field=models.URLField(verbose_name='API Endpoint'),
        ),
        migrations.AlterField(
            model_name='location',
            name='resource_url',
            field=models.URLField(verbose_name='URL of Resource'),
        ),
    ]
