# Generated by Django 3.1.7 on 2021-03-27 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_viewer', '0003_auto_20210325_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='current_estimated_population',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Current Estimated Population'),
        ),
    ]
